### ISSUE TITLE
Incorrect INK/PAPER colors?

### ISSUE THREAD

**Issue by jlcebrian** [daad-adventure-writer/NAPS#11]
Seems like the Espacial text color is not white like the originals. Also visible in Chichen.

![image](https://github.com/daad-adventure-writer/NAPS/assets/1835141/ee73f41e-69f6-4ecd-aadf-0d341b137911)

This may be the case of parsing the parameter of INK and PAPER directly. In Atari/Amiga DAAD, INK/PAPER do the following:
* INK 0 sets the current color to 0
* INK 1 sets the current color to 15
* INK n sets the current color to n-1 otherwise

This is probably for compatibility with monochrome screens such as PCW. INK 1 sets the ink to 'white' and color 15 is usually white (or close) in AD games.

**Comment by DjMorgul** [comment]
Solved on commit 6e12a10cfc9e for PC. The cause for wrong INK/PAPER colors there, was that NAPS wasn't setting flag 62 with the correct value for indicating VGA graphic mode.

Solved on commit 7f04ffb808db for Amiga and Atari ST. The cause for wrong INK/PAPER colors there, was that DAAD interpreters on those platforms change the palette's order for texts differently than they do on VGA mode for PC.
