### ISSUE TITLE
[Ubuntu 20.04] Resizing SDL window makes interpreter to explode :)

### ISSUE THREAD

**Issue by cibersheep** [daad-adventure-writer/NAPS#3]
- Run `intepreter` with pygame gui
- Resize the window (not maximize)

Expected: interpreter surface resizes or centre
Current behaviour: interpreter crashes

```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "interprete.py", line 1089, in <module>
    bucle_daad_nuevo()
  File "interprete.py", line 198, in bucle_daad_nuevo
    valor = ejecuta_proceso (0)
  File "interprete.py", line 733, in ejecuta_proceso
    valor = ejecuta_pasos (pasos)
  File "interprete.py", line 656, in ejecuta_pasos
    cambioFlujo = ejecuta_condacto (entrada[numCondacto][0], entrada[numCondacto][1])
  File "interprete.py", line 608, in ejecuta_condacto
    valor = funcion (*parametros)  # El * saca los parámetros de la lista
  File "[...]/NAPS/condactos_daad.py", line 194, in c1_PARSE
    return parsea_orden (mode)
  File "interprete.py", line 167, in parsea_orden
    return prepara_orden (True, psi) == True
  File "interprete.py", line 437, in prepara_orden
    orden   = gui.lee_cadena (peticion, orden, timeout, espaciar)
  File "[...]/NAPS/gui_pygame.py", line 560, in lee_cadena
    tecla = espera_tecla (timeout[0])
  File "[...]NAPS/gui_pygame.py", line 469, in espera_tecla
    redimensiona_ventana (evento, copia)
  File "[...]NAPS/gui_pygame.py", line 177, in redimensiona_ventana
    actualizaVentana()
  File "[...]NAPS/gui_pygame.py", line 142, in actualizaVentana
    pygame.transform.scale (ventana, (resolucion[0] * factorEscala, resolucion[1] * factorEscala), escalada)
ValueError: Destination surface not the given width or height.
```

**Comment by DjMorgul** [comment]
Thank you for reporting. I need more details about this, because I can't reproduce it. What were the command line parameters?

**Comment by DjMorgul** [comment]
After we talking privately, it seems to be unexpected behavior of PyGame on your platform, which is changing the size of the surface for the window on window resize (even as far as I understand it, it shouldn't do that) fast enough to have it a different size before the previous screen image can be scaled on it.

**Comment by DjMorgul** [comment]
After the tests we ran with your help, commit 219571e14582d3c95ebd1afb3c597ea17cb61fb6 should fix this.

Please, test it for both increasing and decreasing the scale factor of the window.

**Comment by cibersheep** [comment]
Where are the dancing sheep sticker in here? XD

https://user-images.githubusercontent.com/6640041/156364057-4e3e1566-4be0-4294-8de1-7b348dc53dbe.mp4


Scaling is a bit confusing, but it doesn't crash. Yay! Thanks

**Comment by DjMorgul** [comment]
Okay, thanks for the proof and your help to debug it!
