### ISSUE TITLE
IDE importing DDB issues

### ISSUE THREAD

**Issue by cibersheep** [daad-adventure-writer/NAPS#5]
^__^ how are you?

Two issues here that might be related:

~~1) File filter may need to be case insensitive or set to uppercase?~~

~~- Open the ide `python3 ide_pyqt.py`~~
~~- Base de datos > Importar~~

The OS selection window show no files. This might be specific for Unix systems.
Rename `PART1.DDB` to `PART1.ddb` and the file selector dialog will show that file :)

2) Importing a `*.ddb` will load forever

- Rename `PART1.DDB` to `PART1.ddb`
- Base de datos > Importar
- Select PART1.ddb and open

The ide loads forever. Error message:
```
Traceback (most recent call last):
  File "ide_pyqt.py", line 788, in dialogoImportaBD
    indiceFiltro  = dlg_abrir.filters().indexOf (dlg_abrir.selectedFilter())
AttributeError: 'QFileDialog' object has no attribute 'filters'
```

**Comment by cibersheep** [comment]
Oh, 1 is fixed with the commit: https://github.com/daad-adventure-writer/NAPS/commit/a2fe0371a8d9bd32bc9f0fe42fd7834c617fbd49

**Comment by DjMorgul** [comment]
Thank you for reporting it. These issues should be solved already, number 1 by commit a2fe0371a8d9bd32bc9f0fe42fd7834c617fbd49 and number 2 by commit fa1311cf5474a79c2bdcd6d50594c54ece0608f3

**Comment by cibersheep** [comment]
I just tested with Cozume DBB for PC. It seem to load PROC and VERBS but not the rest.
Started with
`python3 ide_pyqt.py test/PART1.DDB`
tapping on Tablas de procesos, it shows 81 tabs and this message
```
Traceback (most recent call last):
  File "ide_pyqt.py", line 601, in cambiaProceso
    imprimeCondacto (condacto, parametros)
  File "ide_pyqt.py", line 969, in imprimeCondacto
    mensaje = mod_actual.lee_secs_ctrl (mensaje, QChar)
NameError: name 'QChar' is not defined
```

Tapping on Tabla de vocabulario tab, shows no message
Tapping on Mensajes del sistema. de usuario, Descripciones de localidades and de objetos, shows empty list and this message for every row
```
Traceback (most recent call last):
  File "ide_pyqt.py", line 474, in data
    return mod_actual.lee_secs_ctrl (self.listaTextos[index.row()], QChar)
NameError: name 'QChar' is not defined
```

Is this helpful?

**Comment by DjMorgul** [comment]
That's an unrelated issue that was reported on issue #4

**Comment by cibersheep** [comment]
Thanks or sorry... or both :D
