### ISSUE TITLE
Suggestion: make console window close on exit if there is no error

### ISSUE THREAD

**Issue by jlcebrian** [daad-adventure-writer/NAPS#9]
Currently, the "Intérprete NAPS" bat file contains a PAUSE command which causes a CMD window to stay open after exiting a game. I suggest making that pause optional so the window closes automatically if the interpreter exists with no issue.

This could be implemented in the BAT file with an ERRORLEVEL check, so the pause could remain after a crash for example:

```
@echo off
PYTHON\python.exe naps\interprete.py
if ERRORLEVEL 1 pause
```

**Comment by DjMorgul** [comment]
Done in NAPS v23.11
